stages:
  split:
    cmd: python -m ml.make_split
    deps:
      - data/raw_data
      - ml/make_split.py
      - conf/split/config.yaml
    outs:
      - data/splits
  features:
    cmd: python -m ml.build_features
    deps:
      - data/splits
      - ml/build_features/__main__.py
      - ml/build_features/inter.py
      - ml/build_features/items.py
      - ml/build_features/base.py
      - ml/build_features/io.py
      - conf/build_features.yaml
    outs:
      - data/processed_features
  train:
    cmd: python -m ml.train
    deps:
      - data/splits
      - ml/train.py
      - conf/train.yaml
      - conf/config.yaml
    outs:
      - artifacts/model
    metrics:
      - artifacts/metrics.json
  infer:
    cmd: python -m ml.infer
    deps:
      - artifacts/model
      - ml/infer.py
    outs:
      - artifacts/preds_test.parquet
