defaults:
  - _self_
  - data: flat50m
  - split: time
  - model: lgbm
  - pipeline: train

seed: 42
work_dir: .
smoke: false
mlflow:
  tracking_uri: ${work_dir}/mlflow
  experiment: competition
artifacts_dir: ${work_dir}/artifacts
