defaults:
  - recbole

name: dssm

# DSSM — не последовательная модель
is_sequential: false

params:
  # базовые гиперпараметры DSSM (RecBole применит при сборке модели)
  embedding_size: 128
  dropout_prob: 0.2

  # обучение/валидация
  learning_rate: 0.001
  epochs: 10
  train_batch_size: 256
  eval_batch_size: 256

  logging_level: INFO
  eval_step: 1

  recbole_config:
    eval_step: 1
    show_progress: true
    # Для внешнего стрим-лоадера отключаем негативное семплирование
    train_neg_sample_args: null
    eval_neg_sample_args: null

