model: DCNV2
config_overrides:
  device: cpu
  epochs: 10
  train_batch_size: 1024
  eval_batch_size: 512
  learning_rate: 1e-3
  stopping_step: 3
  # DCNv2 specific
  cross_num: 3
  dnn_hidden_units: [256, 128, 64]
  reg_weight: 1e-6
