name: ml-ci
on:
  pull_request:
  push:
    branches: [ main ]
jobs:
  smoke-train-validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install Poetry
        run: |
          pip install poetry
      - name: Install deps
        run: |
          poetry config virtualenvs.in-project true
          poetry install --no-interaction --no-ansi
      - name: Smoke train
        env:
          HYDRA_FULL_ERROR: 1
        run: |
          poetry run python -m ml.train model.name=dummy
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: artifacts
          path: artifacts
